### ISSUE TITLE
/raw/ids/ as submodule

### ISSUE THREAD

**Issue by FredericBlum** [intercontinental-dictionary-series/idssegmented#2]
@LinguList Currently, the /raw/ids/  is added as a submodule. Could you add instructions on how to clone this, or provide an update in which the files are placed there diretly?

**Comment by FredericBlum** [comment]
Or should we rather clone with '--recurse-submodules'? If so, I can add a comment in the NOTES.md

**Comment by LinguList** [comment]
In my opinion, the submodule is only important when doing `cldfbench download`. Integrating it would thus not really be needed, only for those (typically lexibankers) who update the data in the future, right?

**Comment by xrotwang** [comment]
> Or should we rather clone with '--recurse-submodules'? If so, I can add a comment in the NOTES.md

Yes, clone with submodules. The submodule is also important for `lexibank.makecldf`, because the corresponding submodule commit will be recorded in the metadata, thus providing transparent provenance.

**Comment by LinguList** [comment]
Ah, that's how that information enters the cldf! I was always wondering :-D

**Comment by xrotwang** [comment]
I think it would also be good to checkout the submodule to a released version of IDS, probably https://github.com/intercontinental-dictionary-series/ids/releases/tag/v4.3 i.e.
```shell
cd raw/ids
git checkout v4.3
```
