### ISSUE TITLE
Branch missing

### ISSUE THREAD

**Issue by FredericBlum** [intercontinental-dictionary-series/idssegmented#3]
@LinguList I have pushed my changes to a new branch 'release-prep' but the branch does not appear in the repo. Yet, the number of branches is indicated at 2. Another case of permission issues?

```
(release) blum@lingn45w idssegmented % git status
On branch release-prep
Your branch is up to date with 'origin/release-prep'.

nothing to commit, working tree clean
```

**Comment by LinguList** [comment]
I made you admin. So I don't know what it could be otherwise.
