### ISSUE TITLE
Consonant clusters oessetic

### ISSUE THREAD

**Issue by FredericBlum** [intercontinental-dictionary-series/idssegmented#5]
@LinguList Especially with ossetic, we have a consonant cluster problem, with up to 10 consonants. All cases are such in whch the grapheme [y] is converted to /j/. The problem is, that in many other cases this conversion is correct, so it will be difficult to handle this in the orthography profiles. We could proide an ugly work-around by replacing the /y/ for ossetic while creating the cldf-set. Any other ideas or should I implement it like this?

**Comment by FredericBlum** [comment]
Similarly, ahlaothavung has this problerm with grapheme [ɣ]

**Comment by LinguList** [comment]
We should kick those cases out for now.

**Comment by LinguList** [comment]
My suggestion is: `idssegmented` is our base for now, but we go on checking data, kicking out languages, or making new data (like keypano) where we make up for problems, and once we make a new sub-set, like keypano, we kick out the languages from idssegmented.

**Comment by LinguList** [comment]
Essentially, what one must do, to kick out one language, is to set the [Blacklist](https://github.com/intercontinental-dictionary-series/idssegmented/blob/main/etc/languages.csv) column to 1.

**Comment by LinguList** [comment]
So you can address the problem by just doing this for Ossetic and any other suspicious language.

**Comment by LinguList** [comment]
You can add yourself as EDITOR, if you help with this :-)
